### ISSUE TITLE
Peer arguments overloading

### ISSUE THREAD

**Issue by fanatid** [bitpay/bitcore-p2p#46]
In `Peer` constructor `port`, `network` and `relay` is optional arguments. When `port` is `Object` and `network` isn't `undefined` arguments will be overloaded, but only `port` and `network`, not `relay`.

i.e. instead
```js
// overloading stuff
if (port instanceof Object && !network) {
  network = port;
  port = undefined;
}
```
should be something like this
```js
var test = Function.prototype.call.bind(Object.prototype.toString)
---
if (test(network) === '[object Boolean]' && !relay) {
  relay = network
  network = undefined
  if (test(port) === '[object Object]') {
    network = port
    port = undefined
  }
}
if (test(port) === '[object Object]' && !network && !relay) {
  network = port
  port = relay = undefined
}
if (test(port) === '[object Boolean]' && !network && !relay) {
  relay = network
  port = network = undefined
}
```
I'm right?
Of course it's not simple overloading, so it may be better to use `opts` as in `Pool`?

Also `@param` missing for `relay`.

**Comment by maraoz** [comment]
+1
I think we should use an opts object probably

**Comment by braydonf** [comment]
Agree with the options object.

**Comment by braydonf** [comment]
Options object for params included in: https://github.com/bitpay/bitcore-p2p/pull/48
